This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./memoirthesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file memoirthesis.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (36 comparisons).
Generating output file memoirthesis.acr....done (25 lines written, 0 warnings).
Output written in memoirthesis.acr.
Transcript written in memoirthesis.alg.
