This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./project.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file project.acn....done (22 entries accepted, 0 rejected).
Sorting entries....done (105 comparisons).
Generating output file project.acr....done (51 lines written, 0 warnings).
Output written in project.acr.
Transcript written in project.alg.
